groups:
  -
    id: 1
    name: Город без центра
  -
    id: 2
    name: Область
  -
    id: 3
    name: Пригороды
  -
    id: 4
    name: Центр города

areas:
  -
    id: 1
    name: Адмиралтейский
    group: 4
  -
    id: 6
    name: Василеостровский
    group: 4
  -
    id: 7
    name: Выборгский
    group: 1
  -
    id: 39
    name: Калининский
    group: 1
  -
    id: 8
    name: Кировский
    group: 1
  -
    id: 271
    name: Колпинский
    group: 3
  -
    id: 40
    name: Красногвардейский
    group: 1
  -
    id: 41
    name: Красносельский
    group: 1
  -
    id: 272
    name: Кронштадский
    group: 3
  -
    id: 273
    name: Курортный
    group: 3
  -
    id: 42
    name: Московский
    group: 1
  -
    id: 43
    name: Невский
    group: 1
  -
    id: 100
    name: Область
    group: 2
  -
    id: 44
    name: Петроградский
    group: 4
  -
    id: 275
    name: Петродворцовый
    group: 3
  -
    id: 45
    name: Приморский
    group: 1
  -
    id: 276
    name: Пушкинский
    group: 3
  -
    id: 46
    name: Фрунзенский
    group: 1
  -
    id: 47
    name: Центральный
    group: 4

stations:
  -
    id: -1
    name: --- любое ---
  -
    id: 50
    name: Автово
  -
    id: 119
    name: Адмиралтейская
  -
    id: 51
    name: Академическая
  -
    id: 52
    name: Балтийская
  -
    id: 121
    name: Бухарестская
  -
    id: 54
    name: Василеостровская
  -
    id: 56
    name: Владимирская
  -
    id: 115
    name: Волковская
  -
    id: 58
    name: Выборгская
  -
    id: 59
    name: Горьковская
  -
    id: 60
    name: Гостинный двог
  -
    id: 61
    name: Гражданский пр.
  -
    id: 62
    name: Девяткино
  -
    id: 63
    name: Достоевская
  -
    id: 65
    name: Елизаровская
  -
    id: 66
    name: Звездная
  -
    id: 116
    name: Звенигородвская
  -
    id: 67
    name: Кировский завод
  -
    id: 112
    name: Комендантский пр.
  -
    id: 111
    name: Крестовский о-в
  -
    id: 68
    name: Купчино
  -
    id: 69
    name: Ладожская
  -
    id: 71
    name: Ленинский пр.
  -
    id: 72
    name: Лесная
  -
    id: 73
    name: Лиговский пр.
  -
    id: 74
    name: Ломоносовская
  -
    id: 75
    name: Маяковская
  -
    id: 120
    name: Международная
  -
    id: 76
    name: Московская
  -
    id: 77
    name: Московские ворота
  -
    id: 79
    name: Нарвская
  -
    id: 80
    name: Невский пр.
  -
    id: 81
    name: Новочеркасская
  -
    id: 118
    name: Обводный канал
  -
    id: 82
    name: Обухово
  -
    id: 83
    name: Озерки
  -
    id: 84
    name: Парк Победы
  -
    id: 114
    name: Парнас
  -
    id: 85
    name: Петроградская
  -
    id: 86
    name: Пионерская
  -
    id: 49
    name: пл. Ал. Невского
  -
    id: 57
    name: пл. Восстания
  -
    id: 70
    name: пл. Ленина
  -
    id: 78
    name: пл. Мужества
  -
    id: 87
    name: Политехническая
  -
    id: 53
    name: пр. Большевиков
  -
    id: 55
    name: пр. Ветеранов
  -
    id: 90
    name: пр. Просвещения
  -
    id: 88
    name: Приморская
  -
    id: 89
    name: Пролетарская
  -
    id: 91
    name: Пушкинская
  -
    id: 92
    name: Рыбацкое
  -
    id: 93
    name: Садовая
  -
    id: 94
    name: Сенная
  -
    id: 117
    name: Спасская
  -
    id: 95
    name: Спортивная
  -
    id: 96
    name: Старая деревня
  -
    id: 97
    name: Технологич. ин-т
  -
    id: 98
    name: Удельная
  -
    id: 64
    name: ул. Дыбенко
  -
    id: 99
    name: Фрунзенская
  -
    id: 100
    name: Черная речка
  -
    id: 101
    name: Чернышевская
  -
    id: 102
    name: Чкаловская
  -
    id: 103
    name: Электросила
